### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [JaxCodeCademy/prj-rev-bwfs-dasmoto#6]
https://github.com/JaxCodeCademy/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/resources/css/Arts.css#L9-L28

You're repeating a lot of styles in each of these selectors. You should extract and consolidate them into a single CSS rule with a more general selector, like so:

```css
* {
  font-family: Helvetica;
}

h2 {
  font-size: 32px;
  color: white;
}
```
